server:
  port: 8080
  servlet:
    context-path: /api/theater-mgnt

spring:
  application:
    name: theater-mgnt

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.zpjvpfkwbcnszfzdwynf
    password: 3kSE347@123

    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
jwt:
  signerKey: "+PAV/uNVIsN2N1peTkAViUZSSc+t8/wOZQDw8M2+HxBD/2dFy9segSiMPHBr+q97"
  refreshable-duration: 36000
  valid-duration: 3600
otp:
  valid-duration: 10

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173

